[build]
  command = "npm ci && npm run build"
  publish = "dist"
  functions = "netlify/functions"  # Remove this line if not using Netlify Functions

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  # Environment type
  NODE_ENV = "production"
  # Install devDependencies with offline support
  NPM_FLAGS = "--include=dev --prefer-offline"

# Redirects for Single Page Applications (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Role = "all"}

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https:;"

# Environment variables (replace with your actual values)
[context.production.environment]
  NODE_ENV = "production"
  # Add other production environment variables here

[context.deploy-preview.environment]
  NODE_ENV = "staging"
  # Add other preview environment variables here

[context.branch-deploy.environment]
  NODE_ENV = "staging"
  # Add other branch environment variables here
